routes/web.php
<?php

use App\Http\Controllers\BookingController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ChatController;
use App\Http\Controllers\CouponController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\FCMController;
use App\Http\Controllers\HandymanController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\PermissionsController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ProviderController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\SubcategoryController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.admin-lock-screen');
});


Auth::routes();
Route::get('/adminlockscreen', function () {
    return view('auth.admin-lock-screen');
})->name('admin.lock');



Route::group(['middleware' => ['role:admin|provider|handyman']], function () {

    Route::get('/subcategories-list/{category_id}', [ServiceController::class, 'subcategories_list']);

    Route::get('admin/index', [DashboardController::class, 'index'])->name('admin.index');

    Route::controller(ProfileController::class)->group(function(){
        Route::get('profiles', 'index')->name('profiles.index');
        Route::post('profiles/{user}', 'update')->name('profiles.update');
    });

    Route::controller(NotificationController::class)->group(function(){
        Route::get('sort-messages', 'sort_messages')->name('sort.messages');
        Route::get('sort-notifications', 'sort_notifications')->name('sort.notifications');
    });

    Route::controller(ChatController::class)->group(function(){
        Route::get('/chats/index', 'index')->name('chats.index');

        Route::get('/chat-data', 'chat_data')->name('chat.data');
        Route::get('sort-users', 'sort_users')->name('sort.users');
        Route::post('/send-message', 'send_message')->name('message.send');
        Route::post('/update_message_status', 'update_message_status')->name('message.status.update');
    });

    Route::post('/fcm-token', [FCMController::class, 'updateToken'])->name('fcmToken');

    Route::get('/bookings-filter', [BookingController::class, 'filter'])->name('bookings.filter');
});


Route::group(['prefix' => 'provider'], function () {

    Route::group(['middleware' => ['role:provider']], function () {

        Route::get('handymen', [HandymanController::class, 'index'])->name('provider.handymen.index');
        Route::get('handymen/create', [HandymanController::class, 'create'])->name('provider.handymen.create');
        Route::post('handymen/store', [HandymanController::class, 'store'])->name('provider.handymen.store');


        Route::get('bookings', [BookingController::class, 'index'])->name('provider.bookings.index');
        Route::get('bookings/edit/{booking}', [BookingController::class, 'edit'])->name('provider.bookings.edit');
        Route::post('bookings/assign/{booking}', [BookingController::class, 'assign_handyman'])->name('provider.bookings.assign');
        Route::post('bookings/approve/{booking}', [BookingController::class, 'provider_approve'])->name('provider.bookings.approve');
        Route::post('bookings/reject/{booking}', [BookingController::class, 'reject'])->name('provider.bookings.reject');
        Route::post('bookings/finish/{booking}', [BookingController::class, 'finish'])->name('provider.bookings.finish');


        Route::get('services', [ServiceController::class, 'index'])->name('provider.services.index');
        Route::get('services/show/{service}', [ServiceController::class, 'show'])->name('provider.services.show');
        Route::get('services/create', [ServiceController::class, 'create'])->name('provider.services.create');
        Route::post('services/store', [ServiceController::class, 'store'])->name('provider.services.store');

        Route::get('categories', [CategoryController::class, 'index'])->name('provider.categories.index');
        Route::get('subcategories', [SubcategoryController::class, 'index'])->name('provider.subcategories.index');
    });
});


Route::group(['prefix' => 'handyman'], function () {


    Route::group(['middleware' => ['role:handyman']], function () {

        Route::get('bookings', [BookingController::class, 'index'])->name('handyman.bookings.index');
        Route::get('bookings/edit{booking}', [BookingController::class, 'edit'])->name('handyman.bookings.edit');

        Route::get('categories', [CategoryController::class, 'index'])->name('handyman.categories.index');
        Route::get('subcategories', [SubcategoryController::class, 'index'])->name('handyman.subcategories.index');
    });
});


Route::group(['prefix' => 'admin'], function () {

    Route::group(['middleware' => ['role:admin']], function () {

        Route::get('profiles/{id}', [ProfileController::class, 'show'])->name('profiles.show');

        Route::resource('users', UserController::class);
        Route::post('users/disable/{user}', [UserController::class, 'disable'])->name('users.disable');
        Route::post('users/enable/{user}', [UserController::class, 'enable'])->name('users.enable');


        Route::resource('handymen', HandymanController::class);

        Route::resource('providers', ProviderController::class);

        Route::resource('services', ServiceController::class);
        Route::post('services/disable/{service}', [ServiceController::class, 'disable'])->name('services.disable');
        Route::post('services/enable/{service}', [ServiceController::class, 'enable'])->name('services.enable');

        Route::resource('categories', CategoryController::class);
        Route::post('categories/disable/{category}', [CategoryController::class, 'disable'])->name('categories.disable');
        Route::post('categories/enable/{category}', [CategoryController::class, 'enable'])->name('categories.enable');

        Route::resource('subcategories', SubcategoryController::class);
        Route::post('subcategories/disable/{subcategory}', [SubcategoryController::class, 'disable'])->name('subcategories.disable');
        Route::post('subcategories/enable/{subcategory}', [SubcategoryController::class, 'enable'])->name('subcategories.enable');

        Route::resource('bookings', BookingController::class);

        Route::resource('settings', SettingController::class);
        Route::post('settings/disable/{setting}', [SettingController::class, 'disable'])->name('settings.disable');
        Route::post('settings/enable/{setting}', [SettingController::class, 'enable'])->name('settings.enable');

        Route::resource('coupons', CouponController::class);
        Route::post('coupons/disable/{coupon}', [CouponController::class, 'disable'])->name('coupons.disable');
        Route::post('coupons/enable/{coupon}', [CouponController::class, 'enable'])->name('coupons.enable');

        Route::get('notifications/index', [NotificationController::class, 'index'])->name('notifications.index');
        Route::get('notifications/create', [NotificationController::class, 'create'])->name('notifications.create');
        Route::post('notifications/broadcast', [NotificationController::class, 'broadcast_notification'])->name('notifications.broadcast');

        Route::resource('roles', RoleController::class);
        Route::resource('permissions', PermissionsController::class);
    });
});


Route::get('language/{locale}', function ($locale) {
    app()->setLocale($locale);
    session()->put('locale', $locale);
    $dir = $locale === 'en' ? 'ltr' : 'rtl';
    session()->put('dir', $dir);
    return redirect()->back();
});

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use DB;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Route;
use Spatie\Permission\Models\Permission;

class RoleController extends Controller
{

    function __construct()
    {

    }


    public function index(Request $request)
    {
        $roles = Role::all();
        return view('admin.roles.index',compact('roles'));

    }

    public function show(Role $role)
    {
        $role = $role;
        $rolePermissions = $role->permissions;

        return view('admin.roles.show', compact('role', 'rolePermissions'));
    }


    public function create()
    {
        $permissions = Permission::get();
        return view('admin.roles.create', compact('permissions'));
    }


    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|unique:roles,name',
            //'permission' => 'required',
        ]);

        $role = Role::create(['name' => $request->get('name')]);
        $role->syncPermissions($request->get('permission'));

        return redirect()->route('roles.index')
                        ->with('success',__('Role created successfully'));
    }


    public function edit(Role $role)
    {
        $role = $role;
        $rolePermissions = $role->permissions->pluck('name')->toArray();
        $permissions = Permission::get();

        return view('admin.roles.edit', compact('role', 'rolePermissions', 'permissions'));
    }


    public function update(Role $role, Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'permission' => 'required',
        ]);

        $role->update($request->only('name'));

        $role->syncPermissions($request->get('permission'));

        return redirect()->route('roles.index')
                        ->with('success',__('Role updated successfully'));
    }


    public function destroy(Role $role)
    {
        $role->delete();

        return redirect()->route('roles.index')
                        ->with('success',__('Role deleted successfully'));
    }
}

resources/views/admin/roles/create.blade.php
@extends('layouts.dashboard')

@section('content')
@php
    $page = 'roles';
@endphp
    <div class="page-wrapper">
        <!--page-content-wrapper-->
        <div class="page-content-wrapper">
            <div class="page-content">

                <div class="card">
                    <div class="card-body">

                        <div class="card-title">
                            <h2>{{ __('Add new role') }}</h2>
                        </div>
                        <hr />
                        <div>
                            <div class="lead">
                                Add new role and assign permissions.
                            </div>

                            <div class="container mt-4">

                                @if (count($errors) > 0)
                                    <div class="alert alert-danger">
                                        <strong>Whoops!</strong> There were some problems with your input.<br><br>
                                        <ul>
                                            @foreach ($errors->all() as $error)
                                                <li>{{ $error }}</li>
                                            @endforeach
                                        </ul>
                                    </div>
                                @endif

                                <form method="POST" action="{{ route('roles.store') }}">
                                    @csrf
                                    <div class="mb-3">
                                        <label for="name" class="form-label">Name</label>
                                        <input value="{{ old('name') }}" type="text" class="form-control"
                                            name="name" placeholder="Name" required>
                                    </div>

                                    <label for="permissions" class="form-label">Assign Permissions</label>

                                    <table class="table table-striped">
                                        <thead>
                                            <th scope="col" width="1%"><input type="checkbox" name="all_permission">
                                            </th>
                                            <th scope="col" width="20%">Name</th>
                                            <th scope="col" width="1%">Guard</th>
                                        </thead>

                                        @foreach ($permissions as $permission)
                                            <tr>
                                                <td>
                                                    <input type="checkbox" name="permission[{{ $permission->name }}]"
                                                        value="{{ $permission->name }}" class='permission'>
                                                </td>
                                                <td>{{ $permission->name }}</td>
                                                <td>{{ $permission->guard_name }}</td>
                                            </tr>
                                        @endforeach
                                    </table>

                                    <button type="submit" class="btn btn-primary">{{ __('Save') }}</button>
                                    <a href="{{ route('roles.index') }}" class="btn btn-default">{{ __('Cancel') }}</a>
                                </form>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--end page-content-wrapper-->
    </div>
    <!--end page-wrapper-->

@endsection

@section('scripts')
    <script type="text/javascript">
        $(document).ready(function() {
            $('[name="all_permission"]').on('click', function() {

                if ($(this).is(':checked')) {
                    $.each($('.permission'), function() {
                        $(this).prop('checked', true);
                    });
                } else {
                    $.each($('.permission'), function() {
                        $(this).prop('checked', false);
                    });
                }

            });
        });
    </script>
@endsection

resources/views/admin/roles/edit.blade.php
@extends('layouts.dashboard')

@section('content')
@php
    $page = 'roles';
@endphp
    <div class="page-wrapper">
        <!--page-content-wrapper-->
        <div class="page-content-wrapper">
            <div class="page-content">

                <div class="card">
                    <div class="card-body">

                        <div class="card-title">
                            <h2>{{ __('Update role') }}</h2>
                        </div>
                        <hr />
                        <div>

                            <div class="lead">
                                Edit role and manage permissions.
                            </div>

                            <div class="container mt-4">

                                @if (count($errors) > 0)
                                    <div class="alert alert-danger">
                                        <strong>Whoops!</strong> There were some problems with your input.<br><br>
                                        <ul>
                                            @foreach ($errors->all() as $error)
                                                <li>{{ $error }}</li>
                                            @endforeach
                                        </ul>
                                    </div>
                                @endif


                                <form method="POST" action="{{ route('roles.update', $role->id) }}">
                                    @method('patch')
                                    @csrf

                                    <div class="mb-3">
                                        <label for="name" class="form-label">{{ __('Name') }}</label>
                                        <input value="{{ $role->name }}" type="text" class="form-control"
                                            name="name" placeholder="Name" required>
                                    </div>

                                    <label for="permissions" class="form-label">{{ __('Assign Permissions') }}</label>

                                    <table class="table table-striped">
                                        <thead>
                                            <th scope="col" width="1%"><input type="checkbox" name="all_permission">
                                            </th>
                                            <th scope="col" width="20%">Name</th>
                                            <th scope="col" width="1%">Guard</th>
                                        </thead>

                                        @foreach ($permissions as $permission)
                                            <tr>
                                                <td>
                                                    <input type="checkbox" name="permission[{{ $permission->name }}]"
                                                        value="{{ $permission->name }}" class='permission'
                                                        {{ in_array($permission->name, $rolePermissions) ? 'checked' : '' }}>
                                                </td>
                                                <td>{{ $permission->name }}</td>
                                                <td>{{ $permission->guard_name }}</td>
                                            </tr>
                                        @endforeach
                                    </table>

                                    <button type="submit" class="btn btn-primary">{{ __('Save changes') }}</button>
                                    <a href="{{ route('roles.index') }}" class="btn btn-default">{{ __('Cancel') }}</a>
                                </form>
                            </div>



                        </div>
                    </div>
                </div>

            </div>
            <!--end page-content-wrapper-->
        </div>
        <!--end page-wrapper-->
    </div>
@endsection

@section('scripts')
    <script type="text/javascript">
        $(document).ready(function() {
            $('[name="all_permission"]').on('click', function() {

                if ($(this).is(':checked')) {
                    $.each($('.permission'), function() {
                        $(this).prop('checked', true);
                    });
                } else {
                    $.each($('.permission'), function() {
                        $(this).prop('checked', false);
                    });
                }

            });
        });
    </script>
@endsection

resources/views/admin/roles/index.blade.php
@extends('layouts.dashboard')
@section('content')
@php
    $page = 'roles';
@endphp
    <!--page-wrapper-->
    <div class="page-wrapper">
        <!--page-content-wrapper-->
        <div class="page-content-wrapper">
            <div class="page-content">

                <h3>{{ __('Roles\' Management') }}</h3>

                <div class="mt-2">
                    @include('layouts.partials.messages')
                </div>

                <!--breadcrumb-->
                <div class="page-breadcrumb d-none d-md-flex align-items-center mb-3">

                    <div class="lead">

                        <a href="{{ route('roles.create') }}"
                            class="btn btn-primary btn-sm float-right">{{ __('Add new role') }}</a>
                    </div>
                </div>
                <!--end breadcrumb-->


                <div class="card">
                    <div class="card-body">
                        <div class="card-title">
                            <h5>{{ __('ٌRoles table') }}</h5>
                        </div>
                        <hr />
                        <div class="table-responsive">
                            <table id="example" class="table table-striped table-bordered" style="width:100%">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>{{ __('Name') }}</th>

                                        <th></th>
                                        <th></th>
                                        <th></th>

                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($roles as $key => $role)
                                        <tr>
                                            <td>{{ $role->id }}</td>
                                            <td>{{ $role->name }}</td>

                                            <td>
                                                <a href="{{ route('roles.show', $role) }}">
                                                    <i class="fas fa-eye text-success fa-2x"></i>
                                                </a>
                                            </td>
                                            <td>
                                                <a href="{{ route('roles.edit', $role) }}">
                                                    <i class="fa-solid fa-2x fa-pen-to-square"></i>
                                                </a>
                                            </td>

                                            <td>
                                                <a href="{{ route('roles.destroy', $role) }}">
                                                    <i class="fa-solid text-danger fa-2x fa-trash-can"></i>
                                                </a>
                                            </td>



                                        </tr>
                                    @endforeach
                                </tbody>


                            </table>

                        </div>

                    </div>
                </div>


            </div>
        </div>
        <!--end page-content-wrapper-->
    </div>
    <!--end page-wrapper-->
@endsection

resources/views/admin/roles/show.blade.php
@extends('layouts.dashboard')

@section('content')
@php
    $page = 'roles';
@endphp
<div class="page-wrapper">
    <!--page-content-wrapper-->
    <div class="page-content-wrapper">
        <div class="page-content">


    <div class="bg-light p-4 rounded">
        <h1>{{ __(ucfirst($role->name)) }}</h1>
        <div class="lead">

        </div>

        <div class="container mt-4">

            <h3>{{__('Assigned permissions')}}</h3>

            <table class="table table-striped">
                <thead>
                    <th scope="col" width="20%">Name</th>
                    <th scope="col" width="1%">Guard</th>
                </thead>

                @foreach($rolePermissions as $permission)
                    <tr>
                        <td>{{ $permission->name }}</td>
                        <td>{{ $permission->guard_name }}</td>
                    </tr>
                @endforeach
            </table>
        </div>

    </div>


    <div class="mt-4">
        <a href="{{ route('roles.edit', $role->id) }}" class="btn btn-info">{{__('Edit')}}</a>
        <a href="{{ route('roles.index') }}" class="btn btn-default">{{__('Back')}}</a>
    </div>

</div>
</div>
<!--end page-content-wrapper-->
</div>
<!--end page-wrapper-->
@endsection