routes/web.php
<?php

use App\Http\Controllers\BookingController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ChatController;
use App\Http\Controllers\CouponController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\FCMController;
use App\Http\Controllers\HandymanController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\PermissionsController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ProviderController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\SubcategoryController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.admin-lock-screen');
});


Auth::routes();
Route::get('/adminlockscreen', function () {
    return view('auth.admin-lock-screen');
})->name('admin.lock');



Route::group(['middleware' => ['role:admin|provider|handyman']], function () {

    Route::get('/subcategories-list/{category_id}', [ServiceController::class, 'subcategories_list']);

    Route::get('admin/index', [DashboardController::class, 'index'])->name('admin.index');

    Route::controller(ProfileController::class)->group(function(){
        Route::get('profiles', 'index')->name('profiles.index');
        Route::post('profiles/{user}', 'update')->name('profiles.update');
    });

    Route::controller(NotificationController::class)->group(function(){
        Route::get('sort-messages', 'sort_messages')->name('sort.messages');
        Route::get('sort-notifications', 'sort_notifications')->name('sort.notifications');
    });

    Route::controller(ChatController::class)->group(function(){
        Route::get('/chats/index', 'index')->name('chats.index');

        Route::get('/chat-data', 'chat_data')->name('chat.data');
        Route::get('sort-users', 'sort_users')->name('sort.users');
        Route::post('/send-message', 'send_message')->name('message.send');
        Route::post('/update_message_status', 'update_message_status')->name('message.status.update');
    });

    Route::post('/fcm-token', [FCMController::class, 'updateToken'])->name('fcmToken');

    Route::get('/bookings-filter', [BookingController::class, 'filter'])->name('bookings.filter');
});


Route::group(['prefix' => 'provider'], function () {

    Route::group(['middleware' => ['role:provider']], function () {

        Route::get('handymen', [HandymanController::class, 'index'])->name('provider.handymen.index');
        Route::get('handymen/create', [HandymanController::class, 'create'])->name('provider.handymen.create');
        Route::post('handymen/store', [HandymanController::class, 'store'])->name('provider.handymen.store');


        Route::get('bookings', [BookingController::class, 'index'])->name('provider.bookings.index');
        Route::get('bookings/edit/{booking}', [BookingController::class, 'edit'])->name('provider.bookings.edit');
        Route::post('bookings/assign/{booking}', [BookingController::class, 'assign_handyman'])->name('provider.bookings.assign');
        Route::post('bookings/approve/{booking}', [BookingController::class, 'provider_approve'])->name('provider.bookings.approve');
        Route::post('bookings/reject/{booking}', [BookingController::class, 'reject'])->name('provider.bookings.reject');
        Route::post('bookings/finish/{booking}', [BookingController::class, 'finish'])->name('provider.bookings.finish');


        Route::get('services', [ServiceController::class, 'index'])->name('provider.services.index');
        Route::get('services/show/{service}', [ServiceController::class, 'show'])->name('provider.services.show');
        Route::get('services/create', [ServiceController::class, 'create'])->name('provider.services.create');
        Route::post('services/store', [ServiceController::class, 'store'])->name('provider.services.store');

        Route::get('categories', [CategoryController::class, 'index'])->name('provider.categories.index');
        Route::get('subcategories', [SubcategoryController::class, 'index'])->name('provider.subcategories.index');
    });
});


Route::group(['prefix' => 'handyman'], function () {


    Route::group(['middleware' => ['role:handyman']], function () {

        Route::get('bookings', [BookingController::class, 'index'])->name('handyman.bookings.index');
        Route::get('bookings/edit{booking}', [BookingController::class, 'edit'])->name('handyman.bookings.edit');

        Route::get('categories', [CategoryController::class, 'index'])->name('handyman.categories.index');
        Route::get('subcategories', [SubcategoryController::class, 'index'])->name('handyman.subcategories.index');
    });
});


Route::group(['prefix' => 'admin'], function () {

    Route::group(['middleware' => ['role:admin']], function () {

        Route::get('profiles/{id}', [ProfileController::class, 'show'])->name('profiles.show');

        Route::resource('users', UserController::class);
        Route::post('users/disable/{user}', [UserController::class, 'disable'])->name('users.disable');
        Route::post('users/enable/{user}', [UserController::class, 'enable'])->name('users.enable');


        Route::resource('handymen', HandymanController::class);

        Route::resource('providers', ProviderController::class);

        Route::resource('services', ServiceController::class);
        Route::post('services/disable/{service}', [ServiceController::class, 'disable'])->name('services.disable');
        Route::post('services/enable/{service}', [ServiceController::class, 'enable'])->name('services.enable');

        Route::resource('categories', CategoryController::class);
        Route::post('categories/disable/{category}', [CategoryController::class, 'disable'])->name('categories.disable');
        Route::post('categories/enable/{category}', [CategoryController::class, 'enable'])->name('categories.enable');

        Route::resource('subcategories', SubcategoryController::class);
        Route::post('subcategories/disable/{subcategory}', [SubcategoryController::class, 'disable'])->name('subcategories.disable');
        Route::post('subcategories/enable/{subcategory}', [SubcategoryController::class, 'enable'])->name('subcategories.enable');

        Route::resource('bookings', BookingController::class);

        Route::resource('settings', SettingController::class);
        Route::post('settings/disable/{setting}', [SettingController::class, 'disable'])->name('settings.disable');
        Route::post('settings/enable/{setting}', [SettingController::class, 'enable'])->name('settings.enable');

        Route::resource('coupons', CouponController::class);
        Route::post('coupons/disable/{coupon}', [CouponController::class, 'disable'])->name('coupons.disable');
        Route::post('coupons/enable/{coupon}', [CouponController::class, 'enable'])->name('coupons.enable');

        Route::get('notifications/index', [NotificationController::class, 'index'])->name('notifications.index');
        Route::get('notifications/create', [NotificationController::class, 'create'])->name('notifications.create');
        Route::post('notifications/broadcast', [NotificationController::class, 'broadcast_notification'])->name('notifications.broadcast');

        Route::resource('roles', RoleController::class);
        Route::resource('permissions', PermissionsController::class);
    });
});


Route::get('language/{locale}', function ($locale) {
    app()->setLocale($locale);
    session()->put('locale', $locale);
    $dir = $locale === 'en' ? 'ltr' : 'rtl';
    session()->put('dir', $dir);
    return redirect()->back();
});

app/Models/Provider.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Facades\DB;

class Provider extends Model
{
    use HasFactory;

    protected $fillable = [
        'type',
        'description',
        'system_user_id'
    ];


    public function rating()
    {
        $provider_rates = 0;
        $reviews = DB::table('providers_reviews')->where('provider_id', $this->id)->get();
        foreach ($reviews as $review)
        {
            $provider_rates += $review->rate;
        }
        $reviews_count = $reviews->count();
        $provider_rate = $reviews_count == 0 ? 0 : $provider_rates / $reviews_count;

        return $provider_rate;
    }

    /**
     * Get the user that owns the Provider
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class, 'system_user_id', 'id');
    }


    /**
     * Get all of the handymen for the Provider
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function handymen(): HasMany
    {
        return $this->hasMany(Handyman::class, 'provider_id', 'id');
    }

    /**
     * The services that belong to the Provider
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function services(): HasMany
    {
        return $this->hasMany(Service::class);
    }

}

app/Http/Controllers/ProviderController.php
<?php

namespace App\Http\Controllers;

use App\Models\Handyman;
use App\Models\Provider;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Models\Role;

class ProviderController extends Controller
{

    public function index()
    {
        $providers = Provider::all();

        // calculate the rate of each provider
        $providers_ratings = [];
        foreach ($providers as $provider) {
            $provider_rating = $provider->rating();
            $providers_ratings['provider' . $provider->id] = $provider_rating;
        }


        return view('provider.index', compact('providers', 'providers_ratings'));
    }


    public function show(Provider $provider)
    {
        //
    }


    public function create()
    {
        return view('provider.create');
    }


    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'phone' => 'min:10|max:10|regex:/^[0-9]+$/',
            ],
            [
            'name.required' => 'Name field is required',
            'phone.regex' => 'Phone field can be only numbers',
            'phone.min' => 'Phone field must be only 10 numbers',
            'phone.max' => 'Phone field must be only 10 numbers',
        ]);



        $user = User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => $request->password,
            'gender' => $request->gender,
            'phone' => $request->phone == null ? '' : $request->phone,
            'address' => $request->address == null ? '' : $request->address,
            'status' => $request->status,
        ]);

        $role = Role::where('name', 'provider')->value('id');
        $user->syncRoles($role);


        $user->update(['role' => 'provider']);



            Provider::updateOrCreate(
                ['system_user_id' => $user->id],
                    ['system_user_id' => $user->id,
                    'type' => $request->type,
                    'description' => $request->description]
            );


        return redirect()->route('providers.index')
            ->withSuccess(__('Provider created successfully'));
    }



    public function edit(Provider $provider)
    {
        $user = $provider->user;
        return view('provider.edit', [
            'user' => $user,
            'userRole' => $user->roles->pluck('name')->toArray(),
            'roles' => Role::latest()->get(),
            'provider' => $provider
        ]);
    }


    public function update(Request $request, $system_user_id)
    {
        $this->validate($request, [
            'name' => 'required',
            'phone' => 'min:10|max:10|regex:/^[0-9]+$/',
            ],
            [
            'name.required' => 'Name field is required',
            'phone.regex' => 'Phone field can be only numbers',
            'phone.min' => 'Phone field must be only 10 numbers',
            'phone.max' => 'Phone field must be only 10 numbers',
        ]);

        $user = User::where('id', $system_user_id)->first();
        $user->update([
            'name' => $request->name,
            // 'email' => $request->email,
            // 'password' => $request->password,
            'gender' => $request->gender,
            'phone' => $request->phone,
            'address' => $request->address,
            'status' => $request->status
        ]);

        if ($request->password != '' || $request->password != null)
        {
            $user->update([
                'password' => $request->password,
            ]);
        }

        Provider::updateOrCreate(
            ['system_user_id' => $user->id],
                ['description' => $request->description]
        );

        return redirect()->route('providers.index')
            ->withSuccess(__('User updated successfully'));
    }



    public function destroy(Provider $provider)
    {
        //
    }
}

resources/views/provider/create.blade.php
@extends('layouts.dashboard')

@section('content')

@php
    $genderArray = ['Other' , 'Male' , 'Female'];
    $statusArray = ['On' , 'Off'];
    $providerTypeArray = ['Company', 'Freelance'];
@endphp

@php
$page = 'provider';
@endphp

<div class="page-wrapper">
    <!--page-content-wrapper-->
    <div class="page-content-wrapper">
        <div class="page-content">
            <div class="card">
                <div class="card-body">
                    <div>
                        <h2>{{ __('Add new provider') }}</h2>

                        <hr />

                        <form method="POST" action="{{ route('providers.store') }}">
                            @csrf

                            <div class="mb-3">
                                <label for="name" class="form-label">{{__('Name')}}</label>
                                <input value="{{ old('name') }}"
                                    type="text"
                                    class="form-control"
                                    name="name"
                                    placeholder="Name" required>

                                @if ($errors->has('name'))
                                    <span class="text-danger text-left">{{ $errors->first('name') }}</span>
                                @endif
                            </div>

                            <div class="mb-3">
                                <label for="email" class="form-label">{{__('Email')}}</label>
                                <input value="{{ old('email') }}"
                                    type="email"
                                    class="form-control"
                                    name="email"
                                    placeholder="Email address" required>
                                @if ($errors->has('email'))
                                    <span class="text-danger text-left">{{ $errors->first('email') }}</span>
                                @endif
                            </div>

                            <div class="mb-3">
                                <label for="password"
                                    class="form-label">{{ __('Password') }}</label>
                                <div class="input-group" id="show_hide_password">
                                    <input type="password" class="form-control border-end-0"
                                        id="password" name="password" placeholder="Enter Password">
                                    <a href="javascript:;"
                                        class="input-group-text bg-transparent"><i
                                            class="bx bx-hide"></i></a>
                                </div>
                            </div>


                            <div class="mb-3">
                                <label for="gender" class="form-label">{{__('Gender')}}</label>
                                <select class="form-control" name="gender" id="gender">
                                    @foreach ($genderArray as $item)
                                    <option value="{{$item}}">
                                        {{$item}}
                                    </option>
                                    @endforeach
                                </select>
                                @if ($errors->has('gender'))
                                    <span class="text-danger text-left">{{ $errors->first('gender') }}</span>
                                @endif
                            </div>

                            <div class="mb-3">
                                <label for="phone" class="form-label">{{__('Phone Number')}}</label>
                                <input
                                    type="text"
                                    value="{{ old('phone') }}"
                                    class="form-control"
                                    name="phone"
                                    placeholder= "{{__('Phone Number (Optional)')}}" >
                                @if ($errors->has('phone'))
                                    <span class="text-danger text-left">{{ $errors->first('phone') }}</span>
                                @endif
                            </div>

                            <div class="mb-3">
                                <label for="address" class="form-label">{{__('Address')}}</label>
                                <input
                                    type="text"
                                    value="{{ old('address') }}"
                                    class="form-control"
                                    name="address"
                                    placeholder= "{{__('Address (Optional)')}}">
                                @if ($errors->has('address'))
                                    <span class="text-danger text-left">{{ $errors->first('address') }}</span>
                                @endif
                            </div>

                            <div class="mb-3">
                                <label for="description" class="form-label">{{ __('Description') }}</label>
                                <textarea type="text" class="form-control" name="description" rows="3"
                                    placeholder="Provider Description">{{ old('description') }}</textarea>
                                @if ($errors->has('description'))
                                    <span class="text-danger text-left">{{ $errors->first('description') }}</span>
                                @endif
                            </div>

                            <div class="mb-3">
                                <label for="status" class="form-label">{{__('Status')}}</label>
                                <select class="form-control" name="status" id="status">
                                    @foreach ($statusArray as $item)
                                    <option value="{{$item}}">
                                        {{$item}}
                                    </option>
                                    @endforeach
                                </select>
                                @if ($errors->has('status'))
                                    <span class="text-danger text-left">{{ $errors->first('status') }}</span>
                                @endif
                            </div>


                            <div class="mb-3">
                                <label for="role" class="form-label">{{__('Role')}}</label>
                                <select class="form-control" id="role"
                                    name="role" disabled>
                                    <option value="">{{__('Provider')}}</option>
                                </select>
                                @if ($errors->has('role'))
                                    <span class="text-danger text-left">{{ $errors->first('role') }}</span>
                                @endif
                            </div>


                            <div class="mb-3">
                                <label for="status" class="form-label">{{__('Provider Type')}}</label>
                                <select class="form-control" name="type" id="type">
                                    @foreach ($providerTypeArray as $item)
                                    <option value="{{$item}}">
                                        {{$item}}
                                    </option>
                                    @endforeach
                                </select>
                                @if ($errors->has('type'))
                                    <span class="text-danger text-left">{{ $errors->first('type') }}</span>
                                @endif
                            </div>

                            <button type="submit" class="btn btn-primary">{{__('Save')}}</button>
                            <a href="{{ route('providers.index') }}" class="btn btn-default">{{__('Cancel')}}</button>
                        </form>


                    </div>
                </div>
            </div>



        </div>
    </div>
    <!--end page-content-wrapper-->
</div>
<!--end page-wrapper-->

@endsection

<script src="{{ asset('assets/auth/js/jquery.min.js') }}"></script>
<!--Password show & hide js -->
<script>
    $(document).ready(function() {
        $("#show_hide_password a").on('click', function(event) {
            event.preventDefault();
            if ($('#show_hide_password input').attr("type") == "text") {
                $('#show_hide_password input').attr('type', 'password');
                $('#show_hide_password i').addClass("bx-hide");
                $('#show_hide_password i').removeClass("bx-show");
            } else if ($('#show_hide_password input').attr("type") == "password") {
                $('#show_hide_password input').attr('type', 'text');
                $('#show_hide_password i').removeClass("bx-hide");
                $('#show_hide_password i').addClass("bx-show");
            }
        });
    });
</script>

resources/views/provider/index.blade.php
@extends('layouts.dashboard')

@section('content')

@php
$page = 'provider';
@endphp


    <!--page-wrapper-->
    <div class="page-wrapper">
        <!--page-content-wrapper-->
        <div class="page-content-wrapper">
            <div class="page-content">

                <h3>{{ __('Providers\' Management') }}</h3>

                <div class="mt-2">
                    @include('layouts.partials.messages')
                </div>

                <!--breadcrumb-->
                <div class="page-breadcrumb d-none d-md-flex align-items-center mb-3">

                    <div class="lead">

                        <a href="{{ route('providers.create') }}" class="btn btn-primary btn-sm float-right">{{__('Add new provider')}}</a>
                    </div>
                </div>

                </div>
                <!--end breadcrumb-->


                <div class="card">
                    <div class="card-body">
                        <div class="card-title">
                            <h5>{{ __('Providers table') }}</h5>
                        </div>
                        <hr />
                        <div class="table-responsive">
                            <table id="example" class="table table-striped table-bordered" style="width:100%">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>{{ __('Name') }}</th>
                                        <th>{{ __('Email') }}</th>
                                        <th>{{ __('Gender') }}</th>
                                        <th>{{ __('Phone Number') }}</th>
                                        <th>{{ __('Address') }}</th>
                                        <th>{{ __('Description') }}</th>
                                        <th>{{ __('Status') }}</th>
                                        <th>{{ __('Role') }}</th>
                                        <th>{{ __('Type') }}</th>
                                        <th>{{ __('Rate') }}</th>
                                        <th>{{ __('Actions') }}</th>


                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($providers as $provider)
                                        <tr>
                                            <th scope="row">{{ $provider->system_user_id }}</th>
                                            <td>{{ $provider->user->name }}</td>
                                            <td>{{ $provider->user->email }}</td>
                                            <td>{{ $provider->user->gender }}</td>
                                            <td>{{ $provider->user->phone }}</td>
                                            <td>{{ $provider->user->address }}</td>
                                            <td><p>{{ $provider->description }}</p></td>
                                            <td>{{ $provider->user->status }}</td>
                                            <td>{{ $provider->user->role }}</td>
                                            <td>{{ $provider->type }}</td>

                                            <td>{{ $providers_ratings['provider' . $provider->id] }}</td>

                                            <td>
                                                <a href="{{ route('profiles.show', $provider->system_user_id) }}">
                                                    <i class="fas fa-eye text-success fa-2x"></i>
                                                </a>
                                                &nbsp; &nbsp;
                                                <a href="{{ route('providers.edit', $provider) }}">
                                                    <i class="fa-solid fa-2x fa-pen-to-square"></i>
                                                </a>
                                            </td>


                                        </tr>
                                    @endforeach
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th>#</th>
                                        <th>{{ __('Name') }}</th>
                                        <th>{{ __('Email') }}</th>
                                        <th>{{ __('Gender') }}</th>
                                        <th>{{ __('Phone Number') }}</th>
                                        <th>{{ __('Address') }}</th>
                                        <th>{{ __('Description') }}</th>
                                        <th>{{ __('Status') }}</th>
                                        <th>{{ __('Role') }}</th>
                                        <th>{{ __('Type') }}</th>
                                        <th>{{ __('Rate') }}</th>
                                        <th>{{ __('Actions') }}</th>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>


            </div>
        </div>
        <!--end page-content-wrapper-->
    </div>
    <!--end page-wrapper-->
@endsection


@section('script')
 <!--Data Tables js-->
 <script src="{{ asset('assets/auth/plugins/datatable/js/jquery.dataTables.min.js') }}"></script>

 <script>
    $(document).ready(function() {
        $("#toggle-btn").click();
        $('#example').DataTable();
    });
</script>

@endsection