routes/web.php
<?php

use App\Http\Controllers\BookingController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ChatController;
use App\Http\Controllers\CouponController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\FCMController;
use App\Http\Controllers\HandymanController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\PermissionsController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ProviderController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\SubcategoryController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.admin-lock-screen');
});


Auth::routes();
Route::get('/adminlockscreen', function () {
    return view('auth.admin-lock-screen');
})->name('admin.lock');



Route::group(['middleware' => ['role:admin|provider|handyman']], function () {

    Route::get('/subcategories-list/{category_id}', [ServiceController::class, 'subcategories_list']);

    Route::get('admin/index', [DashboardController::class, 'index'])->name('admin.index');

    Route::controller(ProfileController::class)->group(function(){
        Route::get('profiles', 'index')->name('profiles.index');
        Route::post('profiles/{user}', 'update')->name('profiles.update');
    });

    Route::controller(NotificationController::class)->group(function(){
        Route::get('sort-messages', 'sort_messages')->name('sort.messages');
        Route::get('sort-notifications', 'sort_notifications')->name('sort.notifications');
    });

    Route::controller(ChatController::class)->group(function(){
        Route::get('/chats/index', 'index')->name('chats.index');

        Route::get('/chat-data', 'chat_data')->name('chat.data');
        Route::get('sort-users', 'sort_users')->name('sort.users');
        Route::post('/send-message', 'send_message')->name('message.send');
        Route::post('/update_message_status', 'update_message_status')->name('message.status.update');
    });

    Route::post('/fcm-token', [FCMController::class, 'updateToken'])->name('fcmToken');

    Route::get('/bookings-filter', [BookingController::class, 'filter'])->name('bookings.filter');
});


Route::group(['prefix' => 'provider'], function () {

    Route::group(['middleware' => ['role:provider']], function () {

        Route::get('handymen', [HandymanController::class, 'index'])->name('provider.handymen.index');
        Route::get('handymen/create', [HandymanController::class, 'create'])->name('provider.handymen.create');
        Route::post('handymen/store', [HandymanController::class, 'store'])->name('provider.handymen.store');


        Route::get('bookings', [BookingController::class, 'index'])->name('provider.bookings.index');
        Route::get('bookings/edit/{booking}', [BookingController::class, 'edit'])->name('provider.bookings.edit');
        Route::post('bookings/assign/{booking}', [BookingController::class, 'assign_handyman'])->name('provider.bookings.assign');
        Route::post('bookings/approve/{booking}', [BookingController::class, 'provider_approve'])->name('provider.bookings.approve');
        Route::post('bookings/reject/{booking}', [BookingController::class, 'reject'])->name('provider.bookings.reject');
        Route::post('bookings/finish/{booking}', [BookingController::class, 'finish'])->name('provider.bookings.finish');


        Route::get('services', [ServiceController::class, 'index'])->name('provider.services.index');
        Route::get('services/show/{service}', [ServiceController::class, 'show'])->name('provider.services.show');
        Route::get('services/create', [ServiceController::class, 'create'])->name('provider.services.create');
        Route::post('services/store', [ServiceController::class, 'store'])->name('provider.services.store');

        Route::get('categories', [CategoryController::class, 'index'])->name('provider.categories.index');
        Route::get('subcategories', [SubcategoryController::class, 'index'])->name('provider.subcategories.index');
    });
});


Route::group(['prefix' => 'handyman'], function () {


    Route::group(['middleware' => ['role:handyman']], function () {

        Route::get('bookings', [BookingController::class, 'index'])->name('handyman.bookings.index');
        Route::get('bookings/edit{booking}', [BookingController::class, 'edit'])->name('handyman.bookings.edit');

        Route::get('categories', [CategoryController::class, 'index'])->name('handyman.categories.index');
        Route::get('subcategories', [SubcategoryController::class, 'index'])->name('handyman.subcategories.index');
    });
});


Route::group(['prefix' => 'admin'], function () {

    Route::group(['middleware' => ['role:admin']], function () {

        Route::get('profiles/{id}', [ProfileController::class, 'show'])->name('profiles.show');

        Route::resource('users', UserController::class);
        Route::post('users/disable/{user}', [UserController::class, 'disable'])->name('users.disable');
        Route::post('users/enable/{user}', [UserController::class, 'enable'])->name('users.enable');


        Route::resource('handymen', HandymanController::class);

        Route::resource('providers', ProviderController::class);

        Route::resource('services', ServiceController::class);
        Route::post('services/disable/{service}', [ServiceController::class, 'disable'])->name('services.disable');
        Route::post('services/enable/{service}', [ServiceController::class, 'enable'])->name('services.enable');

        Route::resource('categories', CategoryController::class);
        Route::post('categories/disable/{category}', [CategoryController::class, 'disable'])->name('categories.disable');
        Route::post('categories/enable/{category}', [CategoryController::class, 'enable'])->name('categories.enable');

        Route::resource('subcategories', SubcategoryController::class);
        Route::post('subcategories/disable/{subcategory}', [SubcategoryController::class, 'disable'])->name('subcategories.disable');
        Route::post('subcategories/enable/{subcategory}', [SubcategoryController::class, 'enable'])->name('subcategories.enable');

        Route::resource('bookings', BookingController::class);

        Route::resource('settings', SettingController::class);
        Route::post('settings/disable/{setting}', [SettingController::class, 'disable'])->name('settings.disable');
        Route::post('settings/enable/{setting}', [SettingController::class, 'enable'])->name('settings.enable');

        Route::resource('coupons', CouponController::class);
        Route::post('coupons/disable/{coupon}', [CouponController::class, 'disable'])->name('coupons.disable');
        Route::post('coupons/enable/{coupon}', [CouponController::class, 'enable'])->name('coupons.enable');

        Route::get('notifications/index', [NotificationController::class, 'index'])->name('notifications.index');
        Route::get('notifications/create', [NotificationController::class, 'create'])->name('notifications.create');
        Route::post('notifications/broadcast', [NotificationController::class, 'broadcast_notification'])->name('notifications.broadcast');

        Route::resource('roles', RoleController::class);
        Route::resource('permissions', PermissionsController::class);
    });
});


Route::get('language/{locale}', function ($locale) {
    app()->setLocale($locale);
    session()->put('locale', $locale);
    $dir = $locale === 'en' ? 'ltr' : 'rtl';
    session()->put('dir', $dir);
    return redirect()->back();
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Category extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'details',
        'status',
        'image'
    ];


    /**
     * Get all of the subcategories for the Category
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function subcategories(): HasMany
    {
        return $this->hasMany(Subcategory::class);
    }

    /**
     * Get all of the services for the Category
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function services(): HasMany
    {
        return $this->hasMany(Service::class);
    }

}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Subcategory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;

class CategoryController extends Controller
{

    public function index()
    {
        $categories = Category::all();

        return view('category.index', compact('categories'));
    }


    public function show(Category $category)
    {
        return view('category.show', compact('category'));
    }

    public function create()
    {
        return view('category.create');
    }


    public function store(Request $request)
    {

        $this->validate($request,
            [
                'name' => 'required',
                'name_ar' => 'required',
                'image' =>  'image|mimes:jpg,png,jpeg|max:2048'],
            [
                'image.image' => 'image',
                'image.mimes' => 'mimes',
                'image.max' => 'max',
            ]
        );

        $category = Category::create([
            'name' => $request->name,
            'name_ar' => $request->name_ar,
            'details' => $request->details,
            'status' => $request->status,
        ]);

        if($request->image != '')
        {
            $image =  time() . '-' . $request->image->getClientOriginalName();
            $request->image->move('images/categories/', $image);

            $image = 'images/categories/' . $image;

            $category->update(['image' => $image]);
        }



        return redirect()->route('categories.index')
            ->withSuccess(__('Category created successfully'));
    }


    public function edit(Category $category)
    {
        return view('category.edit', compact('category'));
    }


    public function update(Request $request, Category $category)
    {

        $this->validate($request,[
            'name' => 'required',
            'image' =>  'image|mimes:jpg,png,jpeg|max:2048'
        ]);

        $old_image = $category->image;
        $new_image = null;
        if($request->has('image'))
        {
            $image = $request->image;
            $new_image = time() . '-' . $request->image->getClientOriginalName();
            $image->move('images/categories/',$new_image);
            //$post->photo = 'uploads/posts/'.$newPhoto;
            File::delete($old_image);
        }

        $image_Store = $new_image == null ? $old_image : 'images/categories/' . $new_image;

        $category->update([
            'name' => $request->name,
            'details' => $request->details,
            'status' => $request->status,
            'image' => $image_Store
        ]);

        return redirect()->route('categories.index')
            ->withSuccess(__('Category updated successfully'));
    }


    public function disable($category_id)
    {
        $category = Category::where('id', $category_id)->first();
        $category->update(['status' => 'Off']);

         return redirect()->route('categories.index')
            ->withSuccess(__('Category Disabled successfully'));
    }

    public function enable($category_id)
    {
        $category = Category::where('id', $category_id)->first();
        $category->update(['status' => 'On']);

         return redirect()->route('categories.index')
            ->withSuccess(__('Category Enabled successfully'));
    }

    public function destroy(Category $category)
    {
        // $category->update(['status' => 'NotAvailable']);
        // foreach($category->subcategories as $subcategory)
        // {
        //     $subcategory->update(['status' => 'NotAvailable']);
        // }
        // return redirect()->route('categories.index')
        //     ->withSuccess(__('Category deleted successfully'));
    }
}

resources/views/category/create.blade.php
@extends('layouts.dashboard')

@section('content')
    @php

        $statusArray = ['On', 'Off'];

    @endphp
@php
$page = 'category';
@endphp
    <div class="page-wrapper">
        <!--page-content-wrapper-->
        <div class="page-content-wrapper">
            <div class="page-content">
                <div class="card">
                    <div class="card-body">
                        <div>
                            <h2>{{ __('Add new category') }}</h2>

                            <hr />

                            <form method="POST" action="{{ route('categories.store') }}" enctype="multipart/form-data">
                                @csrf

                                <div class="mb-3">
                                    <label for="name" class="form-label">{{ __('Name') }}</label>
                                    <input value="{{ old('name') }}" type="text" class="form-control" name="name"
                                        placeholder="Name" required>

                                    @if ($errors->has('name'))
                                        <span class="text-danger text-left">{{ $errors->first('name') }}</span>
                                    @endif
                                </div>

                                <div class="mb-3">
                                    <label for="name_ar" class="form-label">{{ __('Name in Arabic') }}</label>
                                    <input value="{{ old('name_ar') }}" type="text" class="form-control" name="name_ar"
                                        placeholder="Name in Arabic" required>

                                    @if ($errors->has('name_ar'))
                                        <span class="text-danger text-left">{{ $errors->first('name_ar') }}</span>
                                    @endif
                                </div>

                                <div class="mb-3">
                                    <label for="details" class="form-label">{{ __('Details') }}</label>
                                    <textarea type="text" class="form-control" name="details" rows="3"
                                        placeholder="Category Description (optional)"></textarea>
                                    @if ($errors->has('details'))
                                        <span class="text-danger text-left">{{ $errors->first('details') }}</span>
                                    @endif
                                </div>

                                <div class="mb-3">
                                    <label for="status" class="form-label">{{ __('Status') }}</label>
                                    <select class="form-control" name="status" id="status">
                                        @foreach ($statusArray as $item)
                                            <option value="{{ $item }}">
                                                {{ $item }}
                                            </option>
                                        @endforeach
                                    </select>
                                    @if ($errors->has('status'))
                                        <span class="text-danger text-left">{{ $errors->first('status') }}</span>
                                    @endif
                                </div>

                                <div class="mb-3">
                                    <label for="image" class="form-label">{{ __('Image') }}</label>
                                    <input type="file" class="form-control" name="image" />
                                    @if ($errors->has('image'))
                                        <span class="text-danger text-left">{{ $errors->first('image') }}</span>
                                    @endif
                                    <input type="hidden" name="hidden_image" />
                                </div>

                                <button type="submit" class="btn btn-primary">{{ __('Save') }}</button>
                                <a href="{{ route('categories.index') }}"
                                    class="btn btn-default">{{ __('Cancel') }}</button>
                            </form>


                        </div>
                    </div>
                </div>



            </div>
        </div>
        <!--end page-content-wrapper-->
    </div>
    <!--end page-wrapper-->
@endsection

resources/views/category/edit.blade.php
@extends('layouts.dashboard')

@section('content')
    @php

        $statusArray = ['On', 'Off'];

    @endphp

@php
$page = 'category';
@endphp

    <div class="page-wrapper">
        <!--page-content-wrapper-->
        <div class="page-content-wrapper">
            <div class="page-content">
                <div class="card">
                    <div class="card-body">
                        <div>
                            <h2>{{ __('Update on category: ') . $category->name }}</h2>

                            <hr />

                            <form method="POST" action="{{ route('categories.update', $category) }}"
                                enctype="multipart/form-data">
                                @method('patch')
                                @csrf

                                <div class="mb-3">
                                    <label for="name" class="form-label">{{ __('Name') }}</label>
                                    <input type="text" class="form-control" name="name" value="{{ $category->name }}"
                                        required>

                                    @if ($errors->has('name'))
                                        <span class="text-danger text-left">{{ $errors->first('name') }}</span>
                                    @endif
                                </div>

                                <div class="mb-3">
                                    <label for="name_ar" class="form-label">{{ __('Name in Arabic') }}</label>
                                    <input value="{{ old('name_ar') }}" type="text" class="form-control" name="name_ar"
                                        value="{{ $category->name_ar }} required>

                                    @if ($errors->has('name_ar'))
                                        <span class="text-danger text-left">{{ $errors->first('name_ar') }}</span>
                                    @endif
                                </div>

                                <div class="mb-3">
                                    <label for="details" class="form-label">{{ __('Details') }}</label>
                                    <textarea type="text" class="form-control" name="details" rows="3"
                                        placeholder="Category Description (optional)">{{ $category->details }}</textarea>

                                    @if ($errors->has('details'))
                                        <span class="text-danger text-left">{{ $errors->first('details') }}</span>
                                    @endif
                                </div>

                                <div class="mb-3">
                                    <label for="status" class="form-label">{{ __('Status') }}</label>
                                    <select class="form-control" name="status" id="status">
                                        @foreach ($statusArray as $item)
                                            <option value="{{ $item }}"
                                                {{ $category->status == $item ? 'selected' : '' }}>
                                                {{ $item }}
                                            </option>
                                        @endforeach
                                    </select>
                                    @if ($errors->has('status'))
                                        <span class="text-danger text-left">{{ $errors->first('status') }}</span>
                                    @endif
                                </div>

                                <div class="mb-3">
                                    <label for="image" class="form-label">{{ __('Image') }}</label>
                                    <input type="file" class="form-control" name="image" />
                                    @if ($errors->has('image'))
                                        <span class="text-danger text-left">{{ $errors->first('image') }}</span>
                                    @endif

                                    <img src="{{ asset($category->image) }}" width="150" class="img-thumbnail" />
                                    <input type="hidden" name="hidden_image" />
                                </div>

                                <button type="submit" class="btn btn-primary">{{ __('Save') }}</button>
                                <a href="{{ route('categories.index') }}"
                                    class="btn btn-default">{{ __('Cancel') }}</button>
                            </form>


                        </div>
                    </div>
                </div>



            </div>
        </div>
        <!--end page-content-wrapper-->
    </div>
    <!--end page-wrapper-->
@endsection

resources/views/category/index.blade.php
@extends('layouts.dashboard')

@section('content')
    @php
        $page = 'category';
    @endphp
    <!--page-wrapper-->
    <div class="page-wrapper">
        <!--page-content-wrapper-->
        <div class="page-content-wrapper">
            <div class="page-content">

                <h3>{{ __('Categories\' Management') }}</h3>

                <div class="mt-2">
                    @include('layouts.partials.messages')
                </div>

                <!--breadcrumb-->
                <div class="page-breadcrumb d-none d-md-flex align-items-center mb-3">

                    <div class="lead">
                        @if (Auth::user()->role === 'admin')
                            <a href="{{ route('categories.create') }}"
                                class="btn btn-primary btn-sm float-right">{{ __('Add new category') }}</a>
                        @endif
                    </div>

                </div>
                <!--end breadcrumb-->


                <div class="card">
                    <div class="card-body">
                        <div class="card-title">
                            <h5>{{ __('Categories table') }}</h5>
                        </div>
                        <hr />
                        <div class="table-responsive">
                            <table id="example" class="table table-striped table-bordered" style="width:100%">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>{{ __('Name') }}</th>
                                        <th>{{ __('Name in Arabic') }}</th>
                                        <th>{{ __('Details') }}</th>
                                        <th>{{ __('Status') }}</th>
                                        <th>{{ __('Image') }}</th>
                                        <th>{{ __('Actions') }}</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($categories as $category)
                                        <tr>
                                            <th scope="row">{{ $category->id }}</th>
                                            <td>{{ $category->name }}</td>
                                            <td>{{ $category->name_ar }}</td>
                                            <td><p>{{ $category->details }}</p></td>
                                            <td>{{ $category->status }}</td>
                                            <td>
                                                <img src="{{asset($category->image)}}" class="user-img" alt="">
                                            </td>
                                            <td>
                                                @if (Auth::user()->role === 'admin')
                                                    <a href="{{ route('categories.show', $category) }}">
                                                        <i class="fas fa-eye text-success fa-2x"></i>
                                                    </a>
                                                    &nbsp; &nbsp;
                                                    <a href="{{ route('categories.edit', $category) }}">
                                                        <i class="fa-solid fa-2x fa-pen-to-square"></i>
                                                    </a>

                                                    &nbsp; &nbsp;
                                                    @if ($category->status === 'On')
                                                        {!! Form::open([
                                                            'method' => 'POST',
                                                            'route' => ['categories.disable', $category],
                                                            'style' => 'display:inline',
                                                        ]) !!}
                                                        {!! Form::button('<i class="far fa-2x fa-trash-alt icon-size"></i>', [
                                                            'type' => 'submit',
                                                            'class' => 'submit-btn text-danger',
                                                        ]) !!}
                                                        {!! Form::close() !!}
                                                    @else
                                                        {!! Form::open([
                                                            'method' => 'POST',
                                                            'route' => ['categories.enable', $category],
                                                            'style' => 'display:inline',
                                                        ]) !!}
                                                        {!! Form::button('<i class="lni lni-reload"></i>', [
                                                            'type' => 'submit',
                                                            'class' => 'submit-btn text-primary btn-lg',
                                                        ]) !!}
                                                        {!! Form::close() !!}
                                                    @endif
                                                @endif
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th>#</th>
                                        <th>{{ __('Name') }}</th>
                                        <th>{{ __('Name in Arabic') }}</th>
                                        <th>{{ __('Details') }}</th>
                                        <th>{{ __('Status') }}</th>
                                        <th>{{ __('Image') }}</th>
                                        <th>{{ __('Actions') }}</th>


                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>


            </div>
        </div>
        <!--end page-content-wrapper-->
    </div>
    <!--end page-wrapper-->
@endsection


@section('script')
    <!--Data Tables js-->
    <script src="{{ asset('assets/auth/plugins/datatable/js/jquery.dataTables.min.js') }}"></script>

    <script>
        $(document).ready(function() {
            $("#toggle-btn").click();
            $('#example').DataTable();
        });
    </script>
@endsection

resources/views/category/show.blade.php
@extends('layouts.dashboard')
@section('content')
@php
$page = 'category';
@endphp
    <div class="page-wrapper">
        <!--page-content-wrapper-->
        <div class="page-content-wrapper">
            <div class="page-content">
                <!--breadcrumb-->
                <h3>{{ __('Category Information: ') . $category->name }}</h3>

                <div class="mt-2">
                    @include('layouts.partials.messages')
                </div>

                <!--breadcrumb-->
                <div class="page-breadcrumb d-none d-md-flex align-items-center mb-3">

                    <div class="lead">


                    </div>

                </div>
                <!--end breadcrumb-->


                <div class="row">
                    <div class="col-12 col-lg-4 col-xl-4">
                        <div class="card">
                            <img src="{{ asset($category->image) }}" class="card-img-top" alt="...">
                            <div class="card-body">
                                <h2 class="card-title">{{ $category->name }}</h2>
                                <p class="card-text">{{ $category->details }}</p>

                                <hr>
                                <h4 class="card-title">{{ __('Sub Categories') }}</h4>
                                <ul class="list-group list-group-flush">
                                    @foreach ($category->subcategories as $subcategory)
                                        <li class="list-group-item">{{ $subcategory->name }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <!--end row-->


            </div>
        </div>
        <!--end page-content-wrapper-->
    </div>
    <!--end page-wrapper-->
@endsection