routes/web.php
<?php

use App\Http\Controllers\BookingController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ChatController;
use App\Http\Controllers\CouponController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\FCMController;
use App\Http\Controllers\HandymanController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\PermissionsController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ProviderController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\SubcategoryController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.admin-lock-screen');
});


Auth::routes();
Route::get('/adminlockscreen', function () {
    return view('auth.admin-lock-screen');
})->name('admin.lock');



Route::group(['middleware' => ['role:admin|provider|handyman']], function () {

    Route::get('/subcategories-list/{category_id}', [ServiceController::class, 'subcategories_list']);

    Route::get('admin/index', [DashboardController::class, 'index'])->name('admin.index');

    Route::controller(ProfileController::class)->group(function(){
        Route::get('profiles', 'index')->name('profiles.index');
        Route::post('profiles/{user}', 'update')->name('profiles.update');
    });

    Route::controller(NotificationController::class)->group(function(){
        Route::get('sort-messages', 'sort_messages')->name('sort.messages');
        Route::get('sort-notifications', 'sort_notifications')->name('sort.notifications');
    });

    Route::controller(ChatController::class)->group(function(){
        Route::get('/chats/index', 'index')->name('chats.index');

        Route::get('/chat-data', 'chat_data')->name('chat.data');
        Route::get('sort-users', 'sort_users')->name('sort.users');
        Route::post('/send-message', 'send_message')->name('message.send');
        Route::post('/update_message_status', 'update_message_status')->name('message.status.update');
    });

    Route::post('/fcm-token', [FCMController::class, 'updateToken'])->name('fcmToken');

    Route::get('/bookings-filter', [BookingController::class, 'filter'])->name('bookings.filter');
});


Route::group(['prefix' => 'provider'], function () {

    Route::group(['middleware' => ['role:provider']], function () {

        Route::get('handymen', [HandymanController::class, 'index'])->name('provider.handymen.index');
        Route::get('handymen/create', [HandymanController::class, 'create'])->name('provider.handymen.create');
        Route::post('handymen/store', [HandymanController::class, 'store'])->name('provider.handymen.store');


        Route::get('bookings', [BookingController::class, 'index'])->name('provider.bookings.index');
        Route::get('bookings/edit/{booking}', [BookingController::class, 'edit'])->name('provider.bookings.edit');
        Route::post('bookings/assign/{booking}', [BookingController::class, 'assign_handyman'])->name('provider.bookings.assign');
        Route::post('bookings/approve/{booking}', [BookingController::class, 'provider_approve'])->name('provider.bookings.approve');
        Route::post('bookings/reject/{booking}', [BookingController::class, 'reject'])->name('provider.bookings.reject');
        Route::post('bookings/finish/{booking}', [BookingController::class, 'finish'])->name('provider.bookings.finish');


        Route::get('services', [ServiceController::class, 'index'])->name('provider.services.index');
        Route::get('services/show/{service}', [ServiceController::class, 'show'])->name('provider.services.show');
        Route::get('services/create', [ServiceController::class, 'create'])->name('provider.services.create');
        Route::post('services/store', [ServiceController::class, 'store'])->name('provider.services.store');

        Route::get('categories', [CategoryController::class, 'index'])->name('provider.categories.index');
        Route::get('subcategories', [SubcategoryController::class, 'index'])->name('provider.subcategories.index');
    });
});


Route::group(['prefix' => 'handyman'], function () {


    Route::group(['middleware' => ['role:handyman']], function () {

        Route::get('bookings', [BookingController::class, 'index'])->name('handyman.bookings.index');
        Route::get('bookings/edit{booking}', [BookingController::class, 'edit'])->name('handyman.bookings.edit');

        Route::get('categories', [CategoryController::class, 'index'])->name('handyman.categories.index');
        Route::get('subcategories', [SubcategoryController::class, 'index'])->name('handyman.subcategories.index');
    });
});


Route::group(['prefix' => 'admin'], function () {

    Route::group(['middleware' => ['role:admin']], function () {

        Route::get('profiles/{id}', [ProfileController::class, 'show'])->name('profiles.show');

        Route::resource('users', UserController::class);
        Route::post('users/disable/{user}', [UserController::class, 'disable'])->name('users.disable');
        Route::post('users/enable/{user}', [UserController::class, 'enable'])->name('users.enable');


        Route::resource('handymen', HandymanController::class);

        Route::resource('providers', ProviderController::class);

        Route::resource('services', ServiceController::class);
        Route::post('services/disable/{service}', [ServiceController::class, 'disable'])->name('services.disable');
        Route::post('services/enable/{service}', [ServiceController::class, 'enable'])->name('services.enable');

        Route::resource('categories', CategoryController::class);
        Route::post('categories/disable/{category}', [CategoryController::class, 'disable'])->name('categories.disable');
        Route::post('categories/enable/{category}', [CategoryController::class, 'enable'])->name('categories.enable');

        Route::resource('subcategories', SubcategoryController::class);
        Route::post('subcategories/disable/{subcategory}', [SubcategoryController::class, 'disable'])->name('subcategories.disable');
        Route::post('subcategories/enable/{subcategory}', [SubcategoryController::class, 'enable'])->name('subcategories.enable');

        Route::resource('bookings', BookingController::class);

        Route::resource('settings', SettingController::class);
        Route::post('settings/disable/{setting}', [SettingController::class, 'disable'])->name('settings.disable');
        Route::post('settings/enable/{setting}', [SettingController::class, 'enable'])->name('settings.enable');

        Route::resource('coupons', CouponController::class);
        Route::post('coupons/disable/{coupon}', [CouponController::class, 'disable'])->name('coupons.disable');
        Route::post('coupons/enable/{coupon}', [CouponController::class, 'enable'])->name('coupons.enable');

        Route::get('notifications/index', [NotificationController::class, 'index'])->name('notifications.index');
        Route::get('notifications/create', [NotificationController::class, 'create'])->name('notifications.create');
        Route::post('notifications/broadcast', [NotificationController::class, 'broadcast_notification'])->name('notifications.broadcast');

        Route::resource('roles', RoleController::class);
        Route::resource('permissions', PermissionsController::class);
    });
});


Route::get('language/{locale}', function ($locale) {
    app()->setLocale($locale);
    session()->put('locale', $locale);
    $dir = $locale === 'en' ? 'ltr' : 'rtl';
    session()->put('dir', $dir);
    return redirect()->back();
});

app/Models/Setting.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
    use HasFactory;

    protected $fillable = [
        'key',
        'value',
        'status'
    ];
}

app/Http/Controllers/SettingController.php
<?php

namespace App\Http\Controllers;

use App\Models\Setting;
use Illuminate\Http\Request;

class SettingController extends Controller
{

    public function index()
    {
        $settings = Setting::all();
        return view('setting.index', compact('settings'));
    }


    public function create()
    {
        //return view('setting.create');
    }


    public function store(Request $request)
    {
        $this->validate($request,[
            //'key' => 'required',
            //'value' => 'required'
        ]);

        $setting = Setting::create([
            //'key' => $request->key,
            // 'value' => $request->value,
            // 'status' => $request->status,
        ]);

        return redirect()->route('settings.index')
            ->withSuccess(__('Setting created successfully'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }


    public function edit(Setting $setting)
    {
        return view('setting.edit', compact('setting'));
    }


    public function update(Request $request, Setting $setting)
    {
        $this->validate($request,[
            //'key' => 'required',
            'value' => 'required'
        ]);

        $setting->update([
            //'key' => $request->key,
            'value' => $request->value,
            //'status' => $request->status,
        ]);

        return redirect()->route('settings.index')
            ->withSuccess(__('Setting updated successfully'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }


    public function disable($setting_id)
    {
        $setting = Setting::where('id', $setting_id)->first();
        $setting->update(['status' => 'Off']);

         return redirect()->route('settings.index')
            ->withSuccess(__('Setting Disabled successfully'));
    }

    public function enable($setting_id)
    {
        $setting = Setting::where('id', $setting_id)->first();
        $setting->update(['status' => 'On']);

         return redirect()->route('settings.index')
            ->withSuccess(__('Setting Enabled successfully'));
    }
}

resources/views/setting/create.blade.php
@extends('layouts.dashboard')

@section('content')
    @php

        $statusArray = ['On', 'Off'];

    @endphp


@php
$page = 'setting';
@endphp

    <div class="page-wrapper">
        <!--page-content-wrapper-->
        <div class="page-content-wrapper">
            <div class="page-content">
                <div class="card">
                    <div class="card-body">
                        <div>
                            <h2>{{ __('Add new setting') }}</h2>

                            <hr />

                            <form method="POST" action="{{ route('settings.store') }}" enctype="multipart/form-data">
                                @csrf

                                <div class="mb-3">
                                    <label for="key" class="form-label">{{ __('Key') }}</label>
                                    <input value="{{ old('key') }}" type="text" class="form-control" name="key"
                                        placeholder="key" required>

                                    @if ($errors->has('key'))
                                        <span class="text-danger text-left">{{ $errors->first('key') }}</span>
                                    @endif
                                </div>

                                <div class="mb-3">
                                    <label for="value" class="form-label">{{ __('Value') }}</label>
                                    <input value="{{ old('value') }}" type="text" class="form-control" name="value"
                                        placeholder="value" required>

                                    @if ($errors->has('value'))
                                        <span class="text-danger text-left">{{ $errors->first('value') }}</span>
                                    @endif
                                </div>

                                <div class="mb-3">
                                    <label for="status" class="form-label">{{ __('Status') }}</label>
                                    <select class="form-control" name="status" id="status">
                                        @foreach ($statusArray as $item)
                                            <option value="{{ $item }}">
                                                {{ $item }}
                                            </option>
                                        @endforeach
                                    </select>
                                    @if ($errors->has('status'))
                                        <span class="text-danger text-left">{{ $errors->first('status') }}</span>
                                    @endif
                                </div>


                                <button type="submit" class="btn btn-primary">{{ __('Save') }}</button>
                                <a href="{{ route('settings.index') }}"
                                    class="btn btn-default">{{ __('Cancel') }}</button>
                            </form>


                        </div>
                    </div>
                </div>



            </div>
        </div>
        <!--end page-content-wrapper-->
    </div>
    <!--end page-wrapper-->
@endsection

resources/views/setting/edit.blade.php
@extends('layouts.dashboard')

@section('content')

@php

    $statusArray = ['On' , 'Off'];

@endphp

@php
$page = 'setting';
@endphp

<div class="page-wrapper">
    <!--page-content-wrapper-->
    <div class="page-content-wrapper">
        <div class="page-content">
            <div class="card">
                <div class="card-body">
                    <div>
                        <h2>{{ __('Update on setting: ') . $setting->key }}</h2>

                        <hr />

                        <form method="POST" action="{{ route('settings.update', $setting) }}">
                            @method('patch')
                            @csrf

                            <div class="mb-3">
                                <label for="key" class="form-label">{{__('Key')}}</label>
                                <input type="text" class="form-control" name="key"
                                    value="{{$setting->key}}"
                                    disabled>

                                @if ($errors->has('key'))
                                    <span class="text-danger text-left">{{ $errors->first('key') }}</span>
                                @endif
                            </div>

                            <div class="mb-3">
                                <label for="value" class="form-label">{{__('Value')}}</label>
                                <input type="text" class="form-control" name="value"
                                    value="{{$setting->value}}"
                                    required>

                                @if ($errors->has('value'))
                                    <span class="text-danger text-left">{{ $errors->first('value') }}</span>
                                @endif
                            </div>

{{--
                            <div class="mb-3">
                                <label for="status" class="form-label">{{__('Status')}}</label>
                                <select class="form-control" name="status" id="status">
                                    @foreach ($statusArray as $item)
                                    <option value="{{$item}}" {{($setting->status == $item) ? 'selected':''}}>
                                        {{$item}}
                                    </option>
                                    @endforeach
                                </select>
                                @if ($errors->has('status'))
                                    <span class="text-danger text-left">{{ $errors->first('status') }}</span>
                                @endif
                            </div> --}}


                            <button type="submit" class="btn btn-primary">{{__('Save')}}</button>
                            <a href="{{ route('settings.index') }}" class="btn btn-default">{{__('Cancel')}}</button>
                        </form>


                    </div>
                </div>
            </div>



        </div>
    </div>
    <!--end page-content-wrapper-->
</div>
<!--end page-wrapper-->

@endsection

resources/views/setting/index.blade.php
@extends('layouts.dashboard')

@section('content')
    @php
        $page = 'setting';
    @endphp

    <!--page-wrapper-->
    <div class="page-wrapper">
        <!--page-content-wrapper-->
        <div class="page-content-wrapper">
            <div class="page-content">

                <h3>{{ __('Settings\' Management') }}</h3>

                <div class="mt-2">
                    @include('layouts.partials.messages')
                </div>

                <!--breadcrumb-->
                <div class="page-breadcrumb d-none d-md-flex align-items-center mb-3">

                    {{-- <div class="lead">
                        @if (Auth::user()->role === 'admin')
                            <a href="{{ route('settings.create') }}"
                                class="btn btn-primary btn-sm float-right">{{ __('Add new setting') }}</a>
                        @endif
                    </div> --}}

                </div>
                <!--end breadcrumb-->


                <div class="card">
                    <div class="card-body">
                        <div class="card-title">
                            <h5>{{ __('Settings table') }}</h5>
                        </div>
                        <hr />
                        <div class="table-responsive">
                            <table id="example" class="table table-striped table-bordered" style="width:100%">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>{{ __('Key') }}</th>
                                        <th>{{ __('Value') }}</th>
                                        <th>{{ __('Status') }}</th>
                                        <th>{{ __('Actions') }}</th>

                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($settings as $setting)
                                        <tr>
                                            <th scope="row">{{ $setting->id }}</th>
                                            <td>{{ $setting->key }}</td>
                                            <td>{{ $setting->value }}</td>
                                            <td>{{ $setting->status }}</td>
                                            <td>
                                                @if (Auth::user()->role === 'admin')
                                                    {{-- <a href="{{ route('settings.show', $setting) }}">
                                                            <i class="fas fa-eye text-success fa-2x"></i>
                                                        </a>
                                                    &nbsp;  &nbsp; --}}

                                                    <a href="{{ route('settings.edit', $setting) }}">
                                                        <i class="fa-solid fa-2x fa-pen-to-square"></i>
                                                    </a>

                                                    {{-- &nbsp;  &nbsp;
                                                    @if ($setting->status === 'On')

                                                            {!! Form::open([
                                                                'method' => 'POST',
                                                                'route' => ['settings.disable', $setting],
                                                                'style' => 'display:inline',
                                                            ]) !!}
                                                            {!! Form::button('<i class="far fa-2x fa-trash-alt icon-size"></i>', [
                                                                'type' => 'submit',
                                                                'class' => 'submit-btn text-danger',
                                                            ]) !!}
                                                            {!! Form::close() !!}


                                                    @else

                                                            {!! Form::open([
                                                                'method' => 'POST',
                                                                'route' => ['settings.enable', $setting],
                                                                'style' => 'display:inline',
                                                            ]) !!}
                                                            {!! Form::button('<i class="lni lni-reload"></i>', [
                                                                'type' => 'submit',
                                                                'class' => 'submit-btn text-primary btn-lg',
                                                            ]) !!}
                                                            {!! Form::close() !!}

                                                    @endif --}}
                                                @endif
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th>#</th>
                                        <th>{{ __('Key') }}</th>
                                        <th>{{ __('Value') }}</th>
                                        <th>{{ __('Status') }}</th>
                                        <th>{{ __('Actions') }}</th>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--end page-content-wrapper-->
    </div>
    <!--end page-wrapper-->
@endsection



@section('script')
    <!--Data Tables js-->
    <script src="{{ asset('assets/auth/plugins/datatable/js/jquery.dataTables.min.js') }}"></script>

    <script>
        $(document).ready(function() {
            $('#example').DataTable();
        });
    </script>
@endsection